forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/metrics/PrometheusHttpMetrics.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/reader/GarmadonReaderTest.java
test/pom.xml
test/src/main/resources/logback.xml

Also correct little issue about release naming in prometheus and it's usage in graphite

Manage ingestion issue with proto2 event being badly ingest

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/SocketAppender.java

Ensure we close the socket if there is an issue during handshake

---

readers/elasticsearch/src/main/elasticsearch/es/template.json

Add to ES template keyword field on paths so we can aggregate on them

[ES template] Add keyword field for paths

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/handler/EventHandler.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/handler/KafkaHandler.java

Solves https://github.com/criteo/garmadon/issues/30

Compute the size of any message sent to kafka

---

jvm-statistics/core/src/main/java/com/criteo/jvm/JVMStatistics.java

Closes https://github.com/criteo/garmadon/issues/28

JVMStatistics should scheduleAtFixedInterval instead of scheduleAtFixedRate

---

scripts/bump_release.sh

Closes https://github.com/criteo/garmadon/issues/42

Correct bump_release.sh for OSX

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/metrics/PrometheusHttpConsumerMetrics.java
readers/elasticsearch/pom.xml
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java

Improve timeout settings, use sniffer to detect dead nodes and add latency metrics

Improve ES reader

---

readers/hdfs/pom.xml

Also remove "scope compile" from dependencies

[HDFS reader] Build a shaded JAR

---

jvm-statistics/src/main/java/com/criteo/hadoop/garmadon/jvm/statistics/NetworkStatistics.java
jvm-statistics/src/test/java/com/criteo/hadoop/garmadon/jvm/JVMStatisticsTest.java
readers/elasticsearch/src/main/elasticsearch/es/template.json

Add packets & errors information for network

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/CloseableBiConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/FileSystemUtils.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/FileSystemUtilsTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java

The directory seems to be created by default with a local FS, but not with HDFS
Also factor and test the method

[HDFS exporter] Ensure final file's parent directory exists

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

* Using -D options
* Usage updated to show parameters name, description and default value
Closes #58

[HDFS exporter] Main parameters are configurable through command line

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/EventsWithHeader.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

* Remove "path" event type (deprecated)
* Increase final files size
* Increase heartbeat period
* Set heartbeat period as non-multiple of expirer period

[HDFS EXPORTER] Decrease number of output files

---

readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-server-overview.json

Correct network graph in server dashboard

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

Was only global, forgot to add the per-event flavor

[HDFS exporter] Export current running offset per event

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetrics.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java

This will allow to compute alerts based on rates instead of absolute values

[HDFS exporter] Log successfully opened files

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

This is not useful outside of monitoring

Auto-commit for lag monitoring

---

readers/hdfs/pom.xml
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/resources/logback.xml
readers/hdfs/src/main/resources/logging.properties

* Discard INFO messages from ParquetWriter
* Use LogBack instead of Log4J

[HDFS exporter] Clean logging

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java

This is usually indicative of an unrecoverable situation.

[HDFS exporter] Kill the app when failing to close output file

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java
forwarder/src/main/resources/server.properties

Still default to localhost if not set

Provide config to set listening host on forwarder

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/modules/ContainerModule.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/modules/StandaloneModule.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/Tracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/flink/FlinkReporterTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracer.java
checkstyle.xml
frameworks/flink/src/main/java/com/criteo/hadoop/garmadon/flink/GarmadonFlinkConf.java
frameworks/flink/src/main/java/com/criteo/hadoop/garmadon/flink/GarmadonFlinkReporter.java
frameworks/flink/src/main/java/com/criteo/hadoop/garmadon/flink/JobIdentifier.java
jvm-statistics/src/main/java/com/criteo/hadoop/garmadon/jvm/GCNotifications.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenator.java
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/CodeCacheUsage.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/G1GC.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/GCCause.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/HeapUsage.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/Locks.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/Safepoints.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/Threads.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/flink/FlinkCheckpointDuration.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/flink/FlinkHeuristic.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/flink/FlinkHeuristicsManager.java
readers/heuristics/src/main/resources/helps/GCCause.html
schema/src/main/java/com/criteo/hadoop/garmadon/schema/serialization/GarmadonSerialization.java
test/src/main/java/com/criteo/hadoop/garmadon/tool/Extractor.java
test/src/main/java/com/criteo/hadoop/garmadon/tool/TinySampler.java
test/src/main/java/org/apache/hadoop/examples/terasort/TeraGenGarmadon.java

Apply miscellaneaous checkstyle

---

readers/hdfs/pom.xml
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/EventsWithHeader.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java

Do not merge before #119 
2 first commits are part of #119 but are needed for this one

Second MR to implement merge of parquet file on hdfs reader

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/UriHelper.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
test/src/main/docker/garmadon/conf-hdfs-reader/logback.xml

Also improve some reader logging and ensure final folder is created

Fail HDFS exporter when failing to close a file after 5 retries

---

readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-compute.json

Currently we report top 10 users based on alphabetical sort

Report top 10 users on compute dashboard  based on top consumption

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/nodemanager/ContainerResourceMonitoringTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMAppTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContainerTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnable.java

Update agent to not use RMContainerImpl.getFinishedStatus as it is not available in hadoop 3
Use finishedStatus field instead
And also ctach Throwable to avoid NoClass and NoMethod exception to leads to failure on jobs/resourcemanager

Finished status

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnable.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnableTest.java

Details: RMAppAAttempt final status is not null only when application is finished.

Fix null pointer exception in RMContextImplEventRunnable

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetrics.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/OffsetComputer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ExtraMetadataWriteSupport.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/FixedOffsetComputer.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetricsTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java

in three separated dependent commits
The third commit is big. See commit message for details

[HDFS_READER] Fix alerting issues

---

agent/pom.xml

change the package name for shading

Fix package name for guava shading

---

pom.xml
readers/hdfs/pom.xml
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/configurations/HdfsReaderConfiguration.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/configurations/HiveConfiguration.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveClient.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveDriverConsul.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/package-info.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/OffsetComputer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/CloseableWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ExpiringConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/FileSystemUtils.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/HiveProtoParquetWriterWithOffset.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/FixedOffsetComputer.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveClientTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ExpiringConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/HiveProtoParquetWriterWithOffsetTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java
test/src/main/docker/docker-compose.yml

Event day folder has been renamed from $day to day=$day
Current imlplementation doesn't manage schema change
An other MR will be done to support it

 [BREAKING] - Expose Garmadon parquet file on hive 

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/metrics/PrometheusHttpMetrics.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/metrics/PrometheusHttpConsumerMetrics.java

this endpoint will serve as healthchecks for running applications.

add /status to metrics endpoints

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java

This is possibly leaking connections to HDFS

Close all ParquetFileReader instances

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java

Contains also the fix on the test that should have make it fail in the first place

[HDFS-reader] Merge correct files together

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/configurations/KafkaConfiguration.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/reader/GarmadonReaderTest.java
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReaderTest.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java
readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/Heuristics.java
test/src/main/java/com/criteo/hadoop/garmadon/tool/Extractor.java

New section is optional in "kafka", eg.
kafka:
topics: [ 'garmadon_am6' ]

Allow configuring Kafka topic for the HDFS reader

---

agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracerTest.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnableTest.java
frameworks/flink/src/test/java/com/criteo/hadoop/garmadon/flink/GarmadonFlinkReporterTest.java
frameworks/spark/src/test/java/com/criteo/hadoop/garmadon/spark/listener/GarmadonSparkListenerIntegrationTest.java
frameworks/spark/src/test/java/com/criteo/hadoop/garmadon/spark/listener/GarmadonSparkListenerTest.java
pom.xml
readers/common/src/test/java/com/criteo/hadoop/garmadon/reader/GarmadonMessageFiltersTest.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/reader/GarmadonReaderTest.java
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReaderTest.java
readers/hdfs/pom.xml
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/kafka/OffsetResetterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/kafka/PartitionsPauseStateHandlerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/FsBasedCheckpointerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/FileSystemUtilsTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/CodeCacheUsageTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/FileHeuristicTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/G1GCTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/GCCauseTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/HeapUsageTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/LocksTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/SafepointsTest.java
readers/heuristics/src/test/java/com/criteo/hadoop/garmadon/heuristics/ThreadsTest.java

Preparation for hive bump to 2.3

Bump mockito to 4.3.1
