pom.xml
scripts/launch_docker_platform.sh
test/src/main/docker/garmadon/Dockerfile

Netty from 4.1.29.Final to 4.1.30.Final
- https://netty.io/news/2018/09/28/4-1-30-Final.html
ByteBuddy from 1.8.22 to 1.9.2
- https://github.com/raphw/byte-buddy/blob/master/release-notes.md
Oshi from 3.8.3 to 3.9.1
- https://github.com/oshi/oshi/blob/master/CHANGELOG.md
Change-Id: I788a12ba59ec26b4a9bbc92af2138cabdcbd6662

Bump garmadon dependency

---

readers/elasticsearch/src/main/elasticsearch/es/template.json

We are facing issues inserting some events due to bad type:
reason=failed to parse [class_loadtime]]]; nested: ElasticsearchException[Elasticsearch exception
[type=i_o_exception, reason=Numeric value (5.459493036E9) out of range of int (-2147483648 - 2147483647)
Change-Id: I666b08c36a1be24d7aa0d7dffa432fe659868356

Update ES schema to align field type to their java type

---

agent/pom.xml
jvm-statistics/core/src/test/java/com/criteo/jvm/JVMStatisticsTest.java
jvm-statistics/protobuf/src/main/protobuf/JVMStatistics.proto
jvm-statistics/protobuf/src/test/java/com/criteo/jvm/ProtobufGCNotificationsTest.java
jvm-statistics/protobuf/src/test/java/com/criteo/jvm/ProtobufStatisticsSinkTest.java
pom.xml
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/EventHelper.java
schema/src/main/protobuf/container_event.proto
schema/src/main/protobuf/data_access_event.proto
schema/src/main/protobuf/event_header.proto
schema/src/main/protobuf/spark_event.proto

As we do not rely anymore on protobuf from hadoop release
and shade it relocated to a garmadon sub package we can bump it to
proto 3

[Breaking] - Bump protobuf from 2.5.0 to 3.6.1

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java

Especially during the migration from proto  2 to 3 we are seeing millions  of logs like that and it drastically reduce event ingestion.
To monitor this we will add a specific metric in the promethues reader metrics: https://github.com/criteo/garmadon/pull/7

Change log level to debug for garmadon message not deserializable

---

agent/pom.xml
forwarder/pom.xml
readers/common/pom.xml
readers/elasticsearch/pom.xml
readers/heuristics/pom.xml

Since move from our internal build process to github repository we loss
some MANIFEST information like Implementation-Version on which we rely to display
version of garmadon  agent/forwarder on logs and prometheus tags

Update build so MANIFEST.MF contains entry Implementation-Version

---

pom.xml
readers/common/pom.xml
readers/common/src/main/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenator.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenatorTest.java

Allows reading a complex message from Garmadon and outputting it as a single-level object in Protobuf or JSON

Add ProtoConcatenator class for Protobuf & JSON

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/Utils.java

Hostname from containers based on NM env variable is in canonical format
the one from standalone JVM is not leading to different format

Get canonical hostname to ensure having same hostname format

---

Readme.md
agent/src/main/java/com/criteo/hadoop/garmadon/agent/EventAgent.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java
forwarder/src/main/resources/server.properties
test/src/main/docker/docker-compose.yml
test/src/main/docker/garmadon/conf-forwarder/server.properties
test/src/main/docker/garmadon/scripts/entrypoint.sh

As we are using ports from the ephemeral trange ports we often faced issue to start agent
as the ports are already used

Change forwarders ports to not use ones from ephemeral range port

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

This is in fact the buffer size before flushing to disk. Setting it too high (128MB by default)
leads to OoM as entries are stored in-memory. Setting it too low would lead to constant writes.
Also had to set manually pageSize, taking the default value as set the previous constructor

[HDFS exporter] Allow setting Proto Parquet writer's "block size"

---

readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReaderTest.java

Due to this bug uri can be different for same nameservice access and path can contain hdfs namenservice

Add back normalization on FS_EVENT removed when migrating to ProtoConcatenator concatToMap function

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/metrics/PrometheusHttpConsumerMetrics.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetrics.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/monitoring/package-info.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ExpiringConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ExpiringConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffsetTest.java

* Writers expire after a given delay after the start (and not last update)
* Warn if two callbacks are registered for a same GarmadonFilter

[HDFS exporter] Add Prometheus metrics & align behavior with specs

---

agent/pom.xml
agent/src/main/java/com/criteo/hadoop/garmadon/agent/modules/PrestoModule.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/Tracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/presto/PluginClassLoaderTracer.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/presto/package-info.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracerTest.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/presto/PluginClassLoaderTracerTest.java
pom.xml

Presto use specific classloader for plugin with no parent.
This leads to garmadon class not being available for presto plugins
and also all libraries used by a plugin to not be loaded by parent classloader
so not being available for garmadon agent.
Using reflections on FileSystemTracer and ensuring that garmadon agent classes
are loaded from the App classloader and not the plugin one permits to use
trace hdfs call

Add Presto module based on StandaloneModule

---

pom.xml
readers/elasticsearch/pom.xml
readers/hdfs/pom.xml
schema/pom.xml
scripts/launch_docker_platform.sh
test/src/main/docker/docker-compose.yml
test/src/main/docker/garmadon/scripts/entrypoint.sh

Bump dependencies + add hdfs reader on docker test platform:
Netty from 4.1.30 to 4.1.32:
https://netty.io/news/2018/10/30/4-1-31-Final.html
https://netty.io/news/2018/11/29/4-1-32-Final.html
Bytebuddy from 1.9.2 to 1.9.7:
https://github.com/raphw/byte-buddy/blob/master/release-notes.md
Prometheus client from 0.5.0 to 0.6.0
Oshi from 3.9.1 too 3.12.1:
https://github.com/oshi/oshi/blob/master/CHANGELOG.md
Parquet-protobuf from 1.8.1 to 1.8.3:
https://github.com/apache/parquet-mr/blob/master/CHANGES.md
Protobuf-dynamic from 0.9.4 to 1.0.0:
https://github.com/os72/protobuf-dynamic/blob/master/RELEASE_NOTES.md
Elasticsearch from 6.5.3 to 6.5.4
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-6.5.4.html
Jackson from 2.9.7 to 2.9.8 …

Bump dependencies

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/configurations/KafkaConfiguration.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputer.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HdfsOffsetComputerTest.java

Add kafka cluster name in file naming convention.
Be backward compatible.
if kafka.cluster is defined use it for file pattern
else use the old pattern

Support kafka cluster migration in reader-hdfs

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java

Next step would be to fail the app when failing too often. Otherwise a given even type could be
lagging behind by too much

[HDFS EXPORTER] Output the exception when failing to close a consumer

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/FileSystemUtils.java

Currently folders in hdfs temp folder based on UUID are never deleted leading
to lots of files/folders beeing kept on hdfs
On normal run we must ensure that those folders are reclaimed at shutdown

Remove temporary hdfs folder at reader shutdown

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracer.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/hdfs/FileSystemTracerTest.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenator.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenatorTest.java
readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-hdfs.json
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReaderTest.java
schema/src/main/protobuf/data_access_event.proto

Uses enum with three value to help migration (UNKNOWN, FAILURE, SUCCESS). If we were only using a boolean, the default value would be false and there would be no way to distinguish an old event that succeeded from a new one that failed.

Add fs event status

---

readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-spark-job-executors.json
readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-spark-job-stages.json
readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-spark-job.json

- use bars and points instead of lines
- where relevant, add task locality graph
- add shuffle fetch/write wait in runtime view
- add percent repartition graph in runtime view
- add missing "AND executor_id:$executor_id" on the executors dashboard

Apply fixes to spark dashboards

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/ContainerHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/NodemanagerHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/RessourceManagerHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/StandaloneHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/modules/NodeManagerModule.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/modules/ResourceManagerModule.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java
readers/elasticsearch/src/main/elasticsearch/grafana/garmadon-jvm.json
schema/src/main/java/com/criteo/hadoop/garmadon/schema/events/HeaderUtils.java

* Add a tag choice on JVM dashboard
* Add missing header fields on forwarder (user, pid, java main class)
* Turn on JVM statistics on NodeManagerModule
* Add missing header field on nodemanager (java main class)
Replaces https://github.com/criteo/garmadon/pull/121

Add more JVM monitoring

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

Output of HDFS reader is used for long term analysis (capa planning, behaviour change on jobs/users)
So we should prioritize space used on our HDFS cluster for those parquet db
GZIP should reduce storage usage by 20/50%

Change compression codec of parquet file from SNAPPY to GZIP

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/NodemanagerHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/RessourceManagerHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/StandaloneHeader.java
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnable.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java
schema/src/main/java/com/criteo/hadoop/garmadon/schema/events/HeaderUtils.java

No id is set on NM and RM events which leads to all those events going to same
partition which can lead to slow/unballanced partition
No id is set on APPLICATION_EVENT froom resourcemanager which lead to not have
all events from an app_id on the same partition. We use this assumption on
heuristics readers and on ES readers to enrich data

Set header id on all events

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/kafka/OffsetResetter.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/kafka/OffsetResetterTest.java

Instead of dropping them.
From ConsumerRebalanceListener' doc:
"It is guaranteed that all consumer processes will invoke onPartitionsRevoked prior to any
process invoking onPartitionsAssigned. So if offsets or other state is saved in the
onPartitionsRevoked call it is guaranteed to be saved by the time the process taking over
that partition has their onPartitionsAssigned callback called to load the state."
We used to drop because we (actually, I) thought the behavior was the other way around, i.e.
_assigned_ called before _revoked_

[HDFS EXPORTER] Commit pending files when revoking a partition

---

scripts/launch_docker_platform.sh
test/src/main/docker/.env
test/src/main/docker/garmadon/Dockerfile
test/src/main/docker/garmadon/hadoop_conf/yarn-site.xml
test/src/main/docker/garmadon/scripts/entrypoint.sh

In order to validate that garmadon agent/hdfs reader is working fine with hadoop 3 update the docker compose platform to be able to start the hadoop cluster with hadoop 3

Add hadoop 3 to docker test platform

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java

Otherwise, it fails with:
java.lang.RuntimeException: .../0.done is not a Parquet file (too small)

Add a leading dot to checkpoint files to exclude them from the Parquet table

---

agent/pom.xml
agent/src/main/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnable.java
agent/src/test/java/com/criteo/hadoop/garmadon/agent/tracers/hadoop/resourcemanager/RMContextImplEventRunnableTest.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/protobuf/ProtoConcatenator.java
readers/elasticsearch/src/main/resources/template.json
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReaderTest.java
schema/src/main/protobuf/resourcemanager_event.proto

It may be interesting to tag via key value applications running on a hadoop cluster.
Unfortunately, yarn.tags (supported by most frameworks) are a list of string.
This change adds the ability to have special yarn.tags containing a ':' to split key and value.
All those tags will appear in the ApplicationEvent under field user_tags which is a map of
string to string.
It will be exported as nested object on ElasticSearch or Parquet.

Add support for key value yarn.tags

---

readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/EventHelper.java
readers/elasticsearch/src/test/java/com/criteo/hadoop/garmadon/elasticsearch/EventHelperTest.java

If property name is empty we are adding fields section_ to the document.
This leads to some fields like code_, class_... to be added and indexed even if they have empty value.
As they are not usefull we shoulkd just skip them if it is empty

Some of the JVMStats section contains empty property string leading to bad fields beeing added to ES

---

.travis.yml

See build: https://travis-ci.org/criteo/garmadon/jobs/563918444
And https://travis-ci.community/t/error-installing-oraclejdk8-expected-feature-release-number-in-range-of-9-to-14-but-got-8/3766/5

Enforce usage of trusty distrib as oracle 8 deployment failed on xenial one in travis

---

readers/heuristics/src/main/java/com/criteo/hadoop/garmadon/heuristics/Heuristics.java

These metrics are always red ATM.
They are too complex for users to understand and for us to finetune, so we decide to ignore them for now.
JIRA: LAKECOMP-1303

Remove Safepoints & Locks heuristics from the DrElephant exporter

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/metrics/PrometheusHttpConsumerMetrics.java
readers/common/src/test/java/com/criteo/hadoop/garmadon/reader/metrics/PrometheusHttpConsumerMetricsTest.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/HdfsExporter.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/configurations/HdfsReaderConfiguration.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java

Details:
- if one reader stops, all readers are stopped and the program terminates
- garmadon reader creation has been moved to a dedicated factory class
- adapt GarmadonReader to support many instances
- adapt PrometheusMetrics to support multiple KafkaConsumers

[HDFS-READER] Implement multithreading by creating multiple instances of Gramadon reader

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetrics.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/monitoring/PrometheusMetricsTest.java

when the partition has not yet been managed by the instance

Fix null pointer when clearing prometheus partition collectors

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/ProtoParquetWriterWithOffset.java

latest_committed_timestamps can be long to set the initial value and during this interval, the gauge will display 0.
With this commit we will always set the field according to what exists on HDFS and the vlue is calculated befor esetting the gauge.

Fix undesired latest_committed_timestamps value at 0

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java

ExpiringConsumer creation can take time since the latest committed timestamp is taken from the footer of a parquet file on HDFS. This time can get so long that kafka assumes the consumer is dead.
This fix move the partitionPauser.resume after the creation of the ExpiringConsumer.

Fix undesired Kafka rebalance when creating ExpiringConsumer

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/CommittableOffset.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/kafka/PartitionsPauseStateHandler.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumer.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/offset/HeartbeatConsumerTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java

run heartbeat and expirer in the same thread as garmadon reader to avoid deadlock issues.
reduce the scope of some synchronized blocks.

[HDFS-READER] Solve deadlock issue

---

readers/hdfs/pom.xml

applied the same exclusion as https://issues.apache.org/jira/browse/PARQUET-1691
https://github.com/apache/parquet-mr/pull/698
https://github.com/twitter/hadoop-lzo/issues/140
temporary fix until parquet 1.11.0 get released.

Fix missing artifact hadoop-lzo

---

readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/CommittableOffset.java
readers/common/src/main/java/com/criteo/hadoop/garmadon/reader/GarmadonReader.java
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java

As ES reader processes messages in bulk in a separated thread, committing offsets will occur in this other thread and not reader thread. As it touches kafka consumer, it may cause some race condition.
Putting back Synchronized consumer for ES solves this issue.

ES reader requires a synchronized consumer

---

readers/elasticsearch/src/main/resources/template.json

starting with kafka 2.2 metrics un-initialized will send NaN instead of 0
however ES does not support NaN
ignore_malformed with silently discard NaN fieldsw while not discarding the whole document

[Reader-ES] Ignore malformed double values

---

Readme.md
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/ElasticSearchReader.java
readers/elasticsearch/src/main/java/com/criteo/hadoop/garmadon/elasticsearch/configurations/ElasticsearchConfiguration.java
readers/elasticsearch/src/test/resources/garmadon-config.yml
test/src/main/docker/garmadon/conf-es-reader/garmadon-config.yml

Index management will now rely on ES ILM mechanism (https://www.elastic.co/guide/en/elasticsearch/reference/current/index-lifecycle-management.html) to avoid having to maintain different external processes

Add usage of ES index lifecycle on top of garmadon indexes

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java

Kafka server-side quota configuration is only compatible with exact client-id (no regex possible).
PRODUCER_PREFIX_NAME variable is not removed as used in metrics.

Remove the hostname to producer client-id

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/Forwarder.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/channel/ForwarderChannelInitializer.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/handler/CloseHandler.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/handler/EventHandler.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/handler/KafkaHandler.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/kafka/KafkaService.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/message/BroadCastedKafkaMessage.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/message/KafkaMessage.java
forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/metrics/ForwarderEventSender.java
forwarder/src/main/resources/server.properties
forwarder/src/test/java/com/criteo/hadoop/garmadon/forwarder/handler/CloseHandlerTest.java
forwarder/src/test/java/com/criteo/hadoop/garmadon/forwarder/handler/EventHandlerTest.java
forwarder/src/test/java/com/criteo/hadoop/garmadon/forwarder/handler/KafkaHandlerTest.java
schema/src/main/java/com/criteo/hadoop/garmadon/schema/serialization/GarmadonSerialization.java

Sending all events for an application id to all kafka partitions creates a sharding issue and can at worst DDOS a kafka partition master
This commit forces all events to be sent to any partitions. Making so, we lose the possibility to enrich some events with information from other events (such as elastic search reader does).
To cope with this issue, this commit also introduce the possibility to send some specific type of events to all partition.
Sending events to all partitions should be reserved for low frequency events. By default, no event are sent to all partitions.

Send messages to any partitions but some configured types

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveClient.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveQueryExecutor.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveClientTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveQueryExecutorTest.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/hive/SimpleHiveServer.java

* There was a bug executing succesful queries 5 times
* Execution of create table and create partition queries is now cached so that no two identical two of them will be performed.
Limitation is this is in memory, but this should be sufficient.
* Splitted HiveClient between execution and abstraction levels; execute as well as some methods that should be private are still
in the public interface of HiveQueryExecutor because fixing this would cause scope creep

[HDFS READER] Reduce the amount of Hive queries

---

forwarder/src/main/java/com/criteo/hadoop/garmadon/forwarder/kafka/KafkaService.java

Default kafka topic for garmadon forwarder is 'garmadon'. This can
now be overwritten with the 'topic' key in server.properties of
the forwarder.

Allow kafka topic name to be loaded from forwarder config file

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/hive/HiveClient.java

Hive2 has keywords that need backticks quoting
More info in https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-Keywords,Non-reservedKeywordsandReservedKeywords

Adapt CREATE TABLE statement to Hive2

---

pom.xml

Because during maven build:
[ERROR] Failed to execute goal on project garmadon-readers-hdfs:
Could not resolve dependencies for project com.criteo.java:garmadon-readers-hdfs:jar:1.4.0:
Failure to find org.pentaho:pentaho-aggdesigner-algorithm:jar:5.1.5-jhyde
in https://repository.cloudera.com/artifactory/cloudera-repos/
https://repository.cloudera.com/artifactory/cloudera-repos/org/pentaho/pentaho-aggdesign[…]5.1.5-jhyde/pentaho-aggdesigner-algorithm-5.1.5-jhyde.pom gives 404
See official pentaho project:
https://github.com/pentaho/pentaho-aggdesigner/blob/master/pom.xml
Added a new maven repository to pull artifacts

Fix the pentaho dependency for the maven build

---

frameworks/spark/src/main/java/com/criteo/hadoop/garmadon/spark/listener/GarmadonSparkListener.java

Now that attemptNumber has been backported to Spark2.2, we can rediscuss this PR.
The thing is Spark must be released and bump before we release garmadon

Prepare migration to Spark3

---

readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/EventsWithHeader.java
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/ReaderFactory.java

The class requires to have also the header fields

Fix JvmStatisticsHeap serialization to Parquet

---

agent/src/main/java/com/criteo/hadoop/garmadon/agent/headers/ContainerHeader.java

The main class of the executors is now YarnCoarseGrainedExecutorBackend

Fix ContainerHeader for Spark3

---

pom.xml
readers/hdfs/src/main/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriter.java
readers/hdfs/src/test/java/com/criteo/hadoop/garmadon/hdfs/writer/PartitionedWriterTest.java
readers/pom.xml

- upgrade flink client to latest version: new clients handle more gracefully cluster rebalancing. Instead of stopping all kafka consumers, only the one concerned by the rebalance will be stopped and have their offset resetted
- expire consumers using a thread pool: this aims at lowering the time it takes to write files to hdfs by parallelizing those operations
- Fix race on latestMessageTimeForPartitionAndDay access
Note: Module heuristics is also removed as it makes the build fail ont est and is never used

Fix reader hdfs constant partition reassignement

---

jvm-statistics/src/main/java/com/criteo/hadoop/garmadon/jvm/utils/SparkRuntime.java

Do not send exception when failing to retrieve Spark version, send "unknown" instead.

Do not send exception for missing Spark Version
